org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=C:/Program Files/Amazon Corretto/jdk25.0.3_9
org.gradle.java.home=C:/Program Files/Amazon Corretto/jdk25.0.3_9

mod_id=fullbright
mod_name=Fullbright
mod_version=1.0.0
mod_group=com.mayank.fullbright
mod_description=A lightweight Fullbright and Fog Remover mod.
mod_authors=Mayank
mod_license=MIT

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.19.2
fabric_version=0.140.0+1.21.11
java_version=21